### ISSUE TITLE
don't run test/basic.js

### ISSUE THREAD

**Issue by iDoka** [drom/bitfield#1]
I would like to try this utility, but I have some troubles by running:

```
$ node test/basic.js 

/home/proj/2016/bitfield/test/basic.js:25
describe('basic', function () {
^
ReferenceError: describe is not defined
    at Object.<anonymous> (/home/proj/2016/bitfield/test/basic.js:25:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

the install script

```
npm install   
```

was completed successful:

```
$ ls -l  node_modules
chai
eslint
istanbul
jsof
mocha
onml
```

---

my system:
centOS7 x86_64

```
$ node -v
v0.10.42
```

What i'm doing wrong?
PS sorry for stupid question, I'm totaly newbie in js/node matters

**Comment by iDoka** [comment]
I also try another command for runing:

```
 $ npm test

> bitfield@0.0.1 test /home/proj/2016/bitfield
> eslint **/*.js && istanbul cover ./node_modules/mocha/bin/_mocha test


/home/proj/2016/bitfield/test/hello.js
  1:1  error  Use the global form of "use strict"  strict

✖ 1 problem (1 error, 0 warnings)

npm ERR! weird error 1
npm ERR! not ok code 0

```

**Comment by drom** [comment]
@iDoka I have added CLI tool. Please try `bin/bitfield.js test/alpha.json > alpha.svg`

**Comment by iDoka** [comment]
I update source and reinstall tool,
now the tool works fine!
thanks!

**Comment by drom** [comment]
@iDoka good to hear that. I will add more description and examples at some point. Let me know how it fits your needs.
